[API]
openai_api_key = your_openai_api_key_here
openai_base_url = http://127.0.0.1:11434/v1
ollama_api_url = http://localhost:11434/api/generate
ollama_modle = llava-phi3
[Paths]
video_folder = H:\\XLdown\\MoneyPrinterTurbo-Portable-Windows-1.2.1\\MoneyPrinterTurbo\\storage\\cache_videos
output_json = video_analysis_results.json
cache_file = video_analysis_cache.json

[Parameters]
frame_diff_threshold = 10000
batch_size = 5
max_frames = 60

#ollama run llava-phi3